Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "scripts/provision.sh"
 
  config.vm.define "node1" do |node1|
    node1.vm.box = "centos/7"
    node1.vm.hostname = "host1"
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    node1.vm.network "private_network", ip: "192.168.33.20"

  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "centos/7"
    node2.vm.hostname = "host2"
    node2.vm.network "private_network", ip: "192.168.33.21"
  end
end
